language: go

go:
    - 1.7
    - 1.8
    - 1.9
    - tip
compiler:
    - g++
before_install:
    - TESSERACT=4.00.00dev LEPTONICA=1.74.2 sudo ./testscript/setup.sh
env:
    - LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib
before_script:
    - go get github.com/otiai10/mint
script:
    - go test -v
