language: go
go:
    - 1.7
    - 1.8
    - 1.9
    - tip
services:
    - docker
compiler:
    - g++
before_install:
    - TESSERACT=4.00.00dev LEPTONICA=1.74.2 sudo ./test/script/setup.sh
env:
    - LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib
before_script:
    - go get github.com/otiai10/mint
script:
    - go test -v
    - go test -race -coverprofile=coverage.txt -covermode=atomic
    - ./test/script/runtime.sh --driver docker --verbose
after_success:
    - bash <(curl -s https://codecov.io/bash)
